import { createContext, useContext, useEffect, useState, ReactNode } from 'react';
import { useAuth } from './AuthContext.native';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Language = 'en' | 'zh';

type Translations = {
  [key: string]: string;
};

const translations: Record<Language, Translations> = {
  en: {
    'app.name': 'Mirror',
    'app.tagline': 'Reflect on your relationships',
    'capture.title': 'Capture a Moment',
    'capture.subtitle': 'Reflect on a recent interaction',
    'capture.who': 'Who was this with?',
    'capture.selectPerson': 'Select a person...',
    'capture.addNewPerson': 'Add new person',
    'capture.what': 'What happened?',
    'capture.whatPlaceholder': 'Briefly describe the interaction...',
    'capture.feel': 'How did it feel?',
    'capture.tags': 'Tags',
    'capture.tagsOptional': '(optional)',
    'capture.tagsPlaceholder': 'Add comma-separated tags...',
    'capture.notes': 'Additional notes',
    'capture.notesOptional': '(optional)',
    'capture.notesPlaceholder': 'Any additional thoughts...',
    'capture.save': 'Save Moment',
    'capture.saving': 'Saving...',
    'capture.success': 'Moment captured successfully',
    'nav.capture': 'Capture',
    'nav.timeline': 'Timeline',
    'nav.patterns': 'Patterns',
    'nav.settings': 'Settings',
    'timeline.title': 'Timeline',
    'timeline.subtitle': 'Your relationship journey',
    'timeline.search': 'Search events, tags, notes...',
    'timeline.allPeople': 'All people',
    'timeline.allEmotions': 'All emotions',
    'timeline.allTypes': 'All types',
    'timeline.allTime': 'All time',
    'timeline.today': 'Today',
    'timeline.yesterday': 'Yesterday',
    'timeline.week': 'Past week',
    'timeline.month': 'Past month',
    'timeline.3months': 'Past 3 months',
    'timeline.noData': 'No moments captured yet',
    'timeline.noResults': 'No moments match your filters',
    'timeline.clearFilters': 'Clear all filters',
    'timeline.person': 'Person',
    'timeline.relationType': 'Relationship Type',
    'timeline.timeFrame': 'Time Frame',
    'patterns.title': 'Pattern Report',
    'patterns.subtitle': 'Observations from your reflections',
    'patterns.week': 'Past Week',
    'patterns.month': 'Past Month',
    'patterns.3months': 'Past 3 Months',
    'patterns.6months': 'Past 6 Months',
    'patterns.year': 'Past Year',
    'patterns.emotionDist': 'Emotion Distribution',
    'patterns.avgIntensity': 'Average intensity',
    'patterns.interactionFreq': 'Interaction Frequency',
    'patterns.commonThemes': 'Common Themes',
    'patterns.moments': 'moments',
    'patterns.noData': 'No data available for this time period',
    'patterns.disclaimer': 'These patterns are observations from your recorded moments. They reflect your experiences without judgment or interpretation. Use them as a starting point for your own reflection.',
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your preferences and data',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language',
    'settings.lightMode': 'Light Mode',
    'settings.darkMode': 'Dark Mode',
    'settings.systemDefault': 'System Default',
    'settings.english': 'English',
    'settings.chinese': '中文 (Chinese)',
    'settings.account': 'Account',
    'settings.signedInAs': 'Signed in as',
    'settings.signOut': 'Sign Out',
    'settings.dataManagement': 'Data Management',
    'settings.exportData': 'Export All Data',
    'settings.exporting': 'Exporting...',
    'settings.deleteData': 'Delete All Data',
    'settings.notifications': 'Notifications',
    'settings.reflectionExperience': 'Reflection Experience',
    'settings.reflectionSubtitle': 'Choose how you want to use Mirror',
    'settings.currentPlan': 'Current plan',
    'settings.planPremium': 'Premium',
    'settings.planFree': 'Free',
    'settings.premiumCopy': 'Guided reflections, quests, XP, badges, and Pro insights',
    'settings.freeCopy': 'Capture moments without quests, XP, or guided reflections',
    'settings.enableReminder': 'Enable daily reminder',
    'settings.time': 'Time',
    'settings.reminderOn': "We'll gently remind you to check in",
    'settings.reminderOff': 'Stay on track with a daily reminder',
    'settings.confirmDelete': 'Confirm Delete',
    'settings.cancel': 'Cancel',
    'settings.deleteWarning': 'This will permanently delete all your events and contacts. This cannot be undone.',
    'settings.privacy': 'Privacy & Security',
    'settings.privacyText1': 'Your data is stored securely and is only accessible by you.',
    'settings.privacyText2': 'Mirror uses industry-standard encryption to protect your information. All data is isolated using Row Level Security.',
    'settings.disclaimer': 'Important Notice',
    'settings.disclaimerText1': 'Mirror is a personal reflection tool designed to help you observe patterns in your relationships.',
    'settings.disclaimerText2': 'It does not provide therapy, counseling, medical advice, or professional mental health services. If you are experiencing mental health challenges, please consult with a licensed professional.',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Create Account',
    'auth.pleaseWait': 'Please wait...',
    'auth.haveAccount': 'Already have an account? Sign in',
    'auth.noAccount': "Don't have an account? Sign up",
    'auth.disclaimer': 'Mirror is a personal reflection tool. It does not provide therapy, counseling, or medical advice.',
    'emotion.happy': 'Happy',
    'emotion.sad': 'Sad',
    'emotion.angry': 'Angry',
    'emotion.anxious': 'Anxious',
    'emotion.calm': 'Calm',
    'emotion.confused': 'Confused',
    'emotion.neutral': 'Neutral',
    'emotion.hurt': 'Hurt',
    'emotion.excited': 'Excited',
    'emotion.frustrated': 'Frustrated',
    'emotion.loved': 'Loved',
    'emotion.disappointed': 'Disappointed',
    'emotion.overwhelmed': 'Overwhelmed',
    'relationship.partner': 'Partner',
    'relationship.family': 'Family',
    'relationship.friend': 'Friend',
    'relationship.work': 'Work',
    'relationship.other': 'Other',
    'contact.name': 'Name',
    'contact.addPerson': 'Add Person',
    'common.loading': 'Loading...',
    'journey.title': 'Your Journey',
    'journey.todayQuests': 'Today\'s Quests',
    'journey.progress': 'Your Progress',
    'journey.level': 'Level',
    'journey.xp': 'XP',
    'journey.streak': 'Day streak',
    'journey.dayLabel': 'Day',
    'journey.badges': 'Badges earned',
    'journey.moments': 'Moments',
    'journey.reflections': 'Reflections',
    'journey.recentBadges': 'Recent Badges',
    'journey.viewAll': 'View All',
    'journey.noBadges': 'No badges earned yet',
    'journey.earnBadges': 'Tap to see what you can earn',
    'journey.nextLevel': 'Next level',
    'journey.maxLevel': 'Max Level Reached!',
    'journey.thisWeek': 'this week',
    'journey.nextUnlock': 'Next unlock',
    'journey.progressTitle': 'Journey Progress',
    'journey.task.logMoment': 'Log a moment',
    'journey.task.answerReflections': "Answer today's reflections",
    'journey.task.reviewPatterns': 'Review your patterns',
    'journey.availableNow': 'Available now',
    'journey.new': 'NEW',
    'journey.progressNote': 'Progress counts distinct days with ≥1 moment logged.',
    'journey.logMoreDays': 'Log on {count} more distinct days',
    'journey.logged': 'You have logged',
    'journey.dailyReflections': 'Daily reflections',
    'journey.dailyReflectionsBenefit': 'Earn XP + a 1-minute insight',
    'journey.emotionTracking': 'Emotion tracking',
    'journey.emotionTrackingBenefit': 'Track intensity over time',
    'journey.patternRecognition': 'Pattern recognition',
    'journey.patternRecognitionBenefit': 'See top themes/triggers',
    'journey.dowPatterns': 'Day-of-week patterns',
    'journey.dowPatternsBenefit': 'Unlock deeper insights',
    'journey.todayPlan': "Today's plan",
    'weekday.sun': 'Sun',
    'weekday.mon': 'Mon',
    'weekday.tue': 'Tue',
    'weekday.wed': 'Wed',
    'weekday.thu': 'Thu',
    'weekday.fri': 'Fri',
    'weekday.sat': 'Sat',
    'patterns.patternReport': 'Pattern Report',
    'patterns.insightsFrom': 'Insights from your reflections',
    'patterns.activeBadge': 'Active Badge',
    'patterns.proInsights': 'Pro Insights',
    'patterns.unlockPro': 'Unlock Pro to see your deeper patterns',
    'patterns.aiInsight': 'AI Pattern Insight',
    'patterns.longTerm': 'Long-term Trend',
    'patterns.relationshipImpact': 'Relationship Impact',
    'patterns.emotionalPhase': 'Emotional Phase',
    'patterns.smartAdvice': 'Smart Advice',
    'patterns.colorWheel': 'Color Wheel Psychology',
    'patterns.summary': 'Summary',
    'patterns.yourPalette': 'Your Color Palette',
    'patterns.momentsLabel': 'Moments',
    'patterns.selectedRange': 'Selected range',
    'patterns.peopleLabel': 'People',
    'patterns.interactedWith': 'Interacted with',
    'patterns.topFeeling': 'Top Feeling',
    'patterns.mostFrequent': 'Most frequent',
    'patterns.avgIntensityLabel': 'Avg Intensity',
    'patterns.emotionalDepth': 'Emotional depth',
    'patterns.levelLabel': 'Level',
    'patterns.emotionOverTime': 'Emotion Intensity Over Time',
    'patterns.emotionDistribution': 'Emotion Distribution',
    'patterns.interactionFrequency': 'Interaction Frequency',
    'patterns.emotionByRelationship': 'Emotion by Relationship',
    'patterns.patternsByDOW': 'Patterns by Day of Week',
    'patterns.recurringThemes': 'Recurring Themes',
    'patterns.noTags': 'No tags used yet',
    'patterns.deepAnalysis': 'Deep Emotional Analysis',
    'patterns.relationshipMap': 'Relationship Influence Map',
    'patterns.trendComparison': 'Long-term Trend Comparison',
    'patterns.aiReport': 'AI Insight Report',
    'common.upgrade': 'Upgrade',
    'capture.viewDetails': 'View details',
    'capture.nextUnlock': 'Next: Day-of-week patterns',
    'capture.levelBadges': 'Level & Badges',
    'capture.quickGuide': 'Quick Guide',
    'capture.personLabel': 'Person:',
    'capture.whatLabel': 'What Happened:',
    'capture.feelLabel': 'How You Felt:',
    'capture.tagsLabel': 'Tags:',
    'capture.dontShowAgain': "Don't show again",
    'capture.attach': 'Attach files or images',
    'capture.chooseColor': 'Choose Your Color',
    'capture.optional': '(optional)',
    'capture.colorMeanings': 'Color Meanings',
    'capture.addDetails': '+ Add details (optional)',
    'capture.levelBadgesTitle': 'Level & Badges',
    'capture.currentLevel': 'Current Level',
    'capture.weeklyXP': 'Weekly XP',
    'capture.moreEmotions': 'More emotions',
    'capture.colorHelp':
      "Each color carries meaning. We've suggested one based on your emotion, but you can pick any color that feels right for this moment.",
    'capture.tagsHelp':
      "Use keywords like 'work', 'family', or 'celebration' to categorize this moment. Tags help group similar experiences in your reports.",
    'colors.red': 'Red',
    'colors.orange': 'Orange',
    'colors.amber': 'Amber',
    'colors.yellow': 'Yellow',
    'colors.lime': 'Lime',
    'colors.green': 'Green',
    'colors.teal': 'Teal',
    'colors.cyan': 'Cyan',
    'colors.blue': 'Blue',
    'colors.indigo': 'Indigo',
    'colors.purple': 'Purple',
    'colors.magenta': 'Magenta',
    'colors.meaning.red': 'Passion, Anger, Energy',
    'colors.meaning.orange': 'Enthusiasm, Warmth, Excitement',
    'colors.meaning.amber': 'Confidence, Success, Pride',
    'colors.meaning.yellow': 'Joy, Optimism, Happiness',
    'colors.meaning.lime': 'Growth, Renewal, Fresh Start',
    'colors.meaning.green': 'Balance, Calm, Harmony',
    'colors.meaning.teal': 'Clarity, Focus, Peace',
    'colors.meaning.cyan': 'Tranquility, Communication',
    'colors.meaning.blue': 'Trust, Stability, Reflection',
    'colors.meaning.indigo': 'Intuition, Wisdom, Depth',
    'colors.meaning.purple': 'Imagination, Spirituality',
    'colors.meaning.magenta': 'Love, Care, Compassion',
    'capture.requiredFieldsWarning':
      'Please fill in the required fields (Person, What Happened, and How You Felt) to save your moment.',
    'badge.unlocked': 'Badge Unlocked',
    'badge.gallery': 'Badge Gallery',
    'badge.earned': 'earned',
    'badge.activeBadge': 'ACTIVE BADGE',
    'badge.removeActive': 'Tap to remove active badge',
    'badge.badges': 'Badges',
    'common.done': 'Done',
    'common.notStarted': 'Not started',
    'common.available': 'Available',
    'badge.gettingStarted': 'Getting Started',
    'badge.consistency': 'Consistency',
    'badge.depth': 'Detail & Depth',
    'badge.emotion': 'Emotional Range',
    'badge.insight': 'Self-Insight',
    'badge.nextBadge': 'Next badge',
    'badge.openGallery': 'Open Badge Gallery',
    'reflection.dailyPrompt': 'Daily Reflection',
    'reflection.support': 'Support',
    'reflection.reframe': 'Reframe',
    'reflection.boundary': 'Boundary',
    'reflection.completed': 'Completed',
    'reflection.skip': 'Skip for now',
    'reflection.continue': 'Continue',
    'reflection.finish': 'Finish',
    'reflection.optional': 'Optional note',
    'reflection.confidence': 'How confident?',
    'reflection.low': 'Low',
    'reflection.medium': 'Medium',
    'reflection.high': 'High',
    'reflection.todayTitle': "Today's Reflections",
    'reflection.completeHint': 'Complete — tap edit to update answers',
    'reflection.quickHint': '3 quick questions to stay mindful',
    'reflection.editCta': 'Edit',
    'reflection.streak': 'Reflection Streak',
    'reflection.longestStreak': 'Longest Streak',
    'reflection.daysCompleted': 'Days completed',
    'reflections.title': "Today's Reflections",
    'reflections.complete': 'Complete! Tap to view insight',
    'reflections.allComplete': 'All reflections complete!',
    'reflections.keepGoing': 'Keep going',
    'reflections.support': 'Do I need outside support?',
    'reflections.reframe': 'What if they meant well?',
    'reflections.boundary': 'Do I need a boundary here?',
    'reflections.done': 'Done',
    'reflections.label.support': 'SELF-CARE',
    'reflections.label.reframe': 'REFRAME',
    'reflections.label.boundary': 'BOUNDARY',
    'reflections.question.support': 'Do I need outside support?',
    'reflections.question.reframe': 'What if they meant well?',
    'reflections.question.boundary': 'Do I need a boundary here?',
    'reflections.answer.Yes,_professional': 'Yes, professional',
    'reflections.answer.Yes,_a_friend': 'Yes, a friend',
    'reflections.answer.Maybe': 'Maybe',
    'reflections.answer.I\'m_okay': "I'm okay",
    'reflections.answer.Unsure': 'Unsure',
    'reflections.answer.Makes_sense': 'Makes sense',
    'reflections.answer.Possible': 'Possible',
    'reflections.answer.Neutral': 'Neutral',
    'reflections.answer.Unlikely': 'Unlikely',
    'reflections.answer.Yes,_right_now': 'Yes, right now',
    'reflections.answer.Maybe_later': 'Maybe later',
    'reflections.answer.No': 'No',
    'reflections.answer.Not_sure': 'Not sure',
    'quest.logMoment': 'Log a moment',
    'quest.answerReflection': 'Complete daily reflection',
    'quest.addDetail': 'Add tags or notes',
    'quest.completed': 'Completed',
    'quest.inProgress': 'In progress',
    'journey.availableNow': 'Available now',
    'journey.new': 'NEW',
    'journey.progressNote': 'Progress counts distinct days with ≥1 moment logged.',
    'journey.logMoreDays': 'Log on {count} more distinct days',
    'journey.logged': 'You have logged',
    'journey.dailyReflections': 'Daily reflections',
    'journey.dailyReflectionsBenefit': 'Earn XP + a 1-minute insight',
    'journey.emotionTracking': 'Emotion tracking',
    'journey.emotionTrackingBenefit': 'Track intensity over time',
    'journey.patternRecognition': 'Pattern recognition',
    'journey.patternRecognitionBenefit': 'See top themes/triggers',
    'journey.dowPatterns': 'Day-of-week patterns',
    'journey.dowPatternsBenefit': 'Unlock deeper insights',
    'journey.todayPlan': "Today's plan",
    'journey.dailyReflections': 'Daily reflections',
    'journey.dailyReflectionsBenefit': 'Earn XP + a 1-minute insight',
    'journey.emotionTracking': 'Emotion tracking',
    'journey.emotionTrackingBenefit': 'Track intensity over time',
    'journey.patternRecognition': 'Pattern recognition',
    'journey.patternRecognitionBenefit': 'See top themes/triggers',
    'xp.howWorks': 'How XP works',
    'xp.logMoment': 'Log a moment',
    'xp.completeReflections': 'Complete daily reflections',
    'xp.depthBonus': 'Depth bonus (2+ details)',
    'xp.oncePerAction': 'XP awarded once per action',
    'levels.beginner': 'Beginner',
    'levels.explorer': 'Explorer',
    'levels.seeker': 'Seeker',
    'levels.adept': 'Adept',
    'levels.navigator': 'Navigator',
    'levels.guide': 'Guide',
    'levels.sage': 'Sage',
  },
  zh: {
    'app.name': 'Mirror',
    'app.tagline': '反思你的人际关系',
    'capture.title': '记录一刻',
    'capture.subtitle': '反思最近的互动',
    'capture.who': '与谁互动?',
    'capture.selectPerson': '选择一个人...',
    'capture.addNewPerson': '添加新联系人',
    'capture.what': '发生了什么?',
    'capture.whatPlaceholder': '简要描述互动...',
    'capture.feel': '感觉如何?',
    'capture.tags': '标签',
    'capture.tagsOptional': '(可选)',
    'capture.tagsPlaceholder': '添加逗号分隔的标签...',
    'capture.notes': '附加笔记',
    'capture.notesOptional': '(可选)',
    'capture.notesPlaceholder': '任何额外的想法...',
    'capture.save': '保存时刻',
    'capture.saving': '保存中...',
    'capture.success': '时刻已成功捕获',
    'nav.capture': '记录',
    'nav.timeline': '时间线',
    'nav.patterns': '模式',
    'nav.settings': '设置',
    'timeline.title': '时间线',
    'timeline.subtitle': '您的互动历史',
    'timeline.search': '搜索时刻...',
    'timeline.allPeople': '所有人',
    'timeline.allEmotions': '所有情绪',
    'timeline.allTypes': '所有类型',
    'timeline.allTime': '所有时间',
    'timeline.today': '今天',
    'timeline.yesterday': '昨天',
    'timeline.week': '过去一周',
    'timeline.month': '过去一个月',
    'timeline.3months': '过去三个月',
    'timeline.noData': '尚未捕获任何时刻',
    'timeline.noResults': '没有符合您筛选条件的时刻',
    'timeline.attachments': '附件',
    'timeline.clearFilters': '清除所有筛选',
    'timeline.person': '人物',
    'timeline.relationType': '关系类型',
    'timeline.timeFrame': '时间范围',
    'patterns.title': '模式报告',
    'patterns.subtitle': '从您的反思中获得见解',
    'patterns.week': '过去一周',
    'patterns.month': '过去一月',
    'patterns.3months': '过去三个月',
    'patterns.6months': '过去六个月',
    'patterns.year': '过去一年',
    'patterns.emotionDist': '情绪分布',
    'patterns.avgIntensity': '平均强度',
    'patterns.interactionFreq': '互动频率',
    'patterns.commonThemes': '常见主题',
    'patterns.moments': '时刻',
    'patterns.noData': '此时间段没有可用数据',
    'patterns.disclaimer': '这些模式是从您记录的时刻中观察到的。它们反映了您的经历，没有判断或解释。将它们用作您自己反思的起点。',
    'settings.title': '设置',
    'settings.subtitle': '管理您的偏好和数据',
    'settings.appearance': '外观',
    'settings.language': '语言',
    'settings.lightMode': '浅色模式',
    'settings.darkMode': '深色模式',
    'settings.systemDefault': '系统默认',
    'settings.english': 'English (英语)',
    'settings.chinese': '中文 (简体)',
    'settings.account': '账户',
    'settings.signedInAs': '已登录为',
    'settings.signOut': '退出登录',
    'settings.dataManagement': '数据管理',
    'settings.exportData': '导出所有数据',
    'settings.exporting': '导出中...',
    'settings.deleteData': '删除所有数据',
    'settings.notifications': '通知',
    'settings.reflectionExperience': '反思体验',
    'settings.reflectionSubtitle': '选择如何使用 Mirror',
    'settings.currentPlan': '当前方案',
    'settings.planPremium': '高级',
    'settings.planFree': '免费',
    'settings.premiumCopy': '引导式反思、任务、XP、徽章和专业洞察',
    'settings.freeCopy': '记录时刻，无任务、XP 或引导反思',
    'settings.enableReminder': '开启每日提醒',
    'settings.time': '时间',
    'settings.reminderOn': '我们会轻柔提醒你打卡',
    'settings.reminderOff': '用每日提醒保持节奏',
    'settings.confirmDelete': '确认删除',
    'settings.cancel': '取消',
    'settings.deleteWarning': '这将永久删除您的所有事件和联系人。此操作无法撤消。',
    'settings.privacy': '隐私与安全',
    'settings.privacyText1': '您的数据安全存储，只有您可以访问。',
    'settings.privacyText2': 'Mirror 使用行业标准加密来保护您的信息。所有数据都通过行级安全性隔离。',
    'settings.disclaimer': '重要声明',
    'settings.disclaimerText1': 'Mirror 是一款个人反思工具，旨在帮助您观察人际关系中的模式。',
    'settings.disclaimerText2': '它不提供治疗、咨询、医疗建议或专业心理健康服务。如果您遇到心理健康挑战，请咨询持牌专业人士。',
    'auth.email': '电子邮件',
    'auth.password': '密码',
    'auth.signIn': '登录',
    'auth.signUp': '创建账户',
    'auth.pleaseWait': '请稍候...',
    'auth.haveAccount': '已有账户？登录',
    'auth.noAccount': '没有账户？注册',
    'auth.disclaimer': 'Mirror 是一款个人反思工具。它不提供治疗、咨询或医疗建议。',
    'emotion.happy': '开心',
    'emotion.sad': '悲伤',
    'emotion.angry': '生气',
    'emotion.anxious': '焦虑',
    'emotion.calm': '平静',
    'emotion.confused': '困惑',
    'emotion.neutral': '中性',
    'emotion.hurt': '受伤',
    'emotion.excited': '兴奋',
    'emotion.frustrated': '沮丧',
    'emotion.loved': '被爱',
    'emotion.disappointed': '失望',
    'emotion.overwhelmed': '不知所措',
    'relationship.partner': '伴侣',
    'relationship.family': '家人',
    'relationship.friend': '朋友',
    'relationship.work': '同事',
    'relationship.other': '其他',
    'contact.name': '姓名',
    'contact.addPerson': '添加人员',
    'common.loading': '加载中...',
    'journey.title': '你的旅程',
    'journey.todayQuests': '今日任务',
    'journey.progress': '你的进度',
    'journey.level': '等级',
    'journey.xp': '经验值',
    'journey.streak': '连续天数',
    'journey.dayLabel': '第',
    'journey.badges': '徽章已获得',
    'journey.moments': '时刻',
    'journey.reflections': '反思',
    'journey.recentBadges': '最近的徽章',
    'journey.viewAll': '查看全部',
    'journey.noBadges': '尚未获得徽章',
    'journey.earnBadges': '点击查看可获得的徽章',
    'journey.nextLevel': '下一级',
    'journey.maxLevel': '已达到最高等级！',
    'journey.thisWeek': '本周',
    'journey.nextUnlock': '下一个解锁',
    'journey.progressTitle': '旅程进度',
    'journey.task.logMoment': '记录一刻',
    'journey.task.answerReflections': '回答今日反思',
    'journey.task.reviewPatterns': '查看你的模式',
    'journey.availableNow': '当前可用',
    'journey.new': '新',
    'journey.progressNote': '进度计算为有记录的不同日期（≥1个时刻）。',
    'journey.logMoreDays': '再记录 {count} 天',
    'journey.logged': '已记录',
    'journey.dailyReflections': '每日反思',
    'journey.dailyReflectionsBenefit': '获得 XP 和 1 分钟洞察',
    'journey.emotionTracking': '情绪跟踪',
    'journey.emotionTrackingBenefit': '随时间跟踪强度',
    'journey.patternRecognition': '模式识别',
    'journey.patternRecognitionBenefit': '查看主要主题/触发点',
    'journey.dowPatterns': '按星期的模式',
    'journey.dowPatternsBenefit': '解锁更深入的洞察',
    'journey.todayPlan': '今日计划',
    'weekday.sun': '周日',
    'weekday.mon': '周一',
    'weekday.tue': '周二',
    'weekday.wed': '周三',
    'weekday.thu': '周四',
    'weekday.fri': '周五',
    'weekday.sat': '周六',
    'patterns.patternReport': '模式报告',
    'patterns.insightsFrom': '反思见解',
    'patterns.activeBadge': '当前徽章',
    'patterns.proInsights': '专业洞察',
    'patterns.unlockPro': '解锁专业版以查看更深入的模式',
    'patterns.aiInsight': 'AI 模式洞察',
    'patterns.longTerm': '长期趋势',
    'patterns.relationshipImpact': '关系影响',
    'patterns.emotionalPhase': '情绪阶段',
    'patterns.smartAdvice': '智能建议',
    'patterns.colorWheel': '色彩心理',
    'patterns.summary': '总结',
    'patterns.yourPalette': '你的色彩',
    'patterns.momentsLabel': '时刻',
    'patterns.selectedRange': '所选范围',
    'patterns.peopleLabel': '人物',
    'patterns.interactedWith': '互动对象',
    'patterns.topFeeling': '最高频情绪',
    'patterns.mostFrequent': '最常见',
    'patterns.avgIntensityLabel': '平均强度',
    'patterns.emotionalDepth': '情感深度',
    'patterns.levelLabel': '等级',
    'patterns.emotionOverTime': '情绪强度随时间',
    'patterns.emotionDistribution': '情绪分布',
    'patterns.interactionFrequency': '互动频率',
    'patterns.emotionByRelationship': '按关系的情绪',
    'patterns.patternsByDOW': '按星期的模式',
    'patterns.recurringThemes': '重复主题',
    'patterns.noTags': '尚未使用标签',
    'patterns.deepAnalysis': '深度情绪分析',
    'patterns.relationshipMap': '关系影响地图',
    'patterns.trendComparison': '长期趋势对比',
    'patterns.aiReport': 'AI 洞察报告',
    'common.upgrade': '升级',
    'capture.viewDetails': '查看详情',
    'capture.nextUnlock': '下一个：按星期的模式',
    'capture.levelBadges': '等级与徽章',
    'capture.quickGuide': '快速指南',
    'capture.personLabel': '人物：',
    'capture.whatLabel': '发生了什么：',
    'capture.feelLabel': '感觉如何：',
    'capture.tagsLabel': '标签：',
    'capture.dontShowAgain': '不再显示',
    'capture.attach': '添加文件或图片',
    'capture.chooseColor': '选择你的颜色',
    'capture.optional': '（可选）',
    'capture.colorMeanings': '颜色含义',
    'capture.addDetails': '+ 添加详情（可选）',
    'capture.levelBadgesTitle': '等级与徽章',
    'capture.currentLevel': '当前等级',
    'capture.weeklyXP': '每周经验值',
    'capture.moreEmotions': '更多情绪',
    'capture.colorHelp': '每种颜色都有含义。我们根据你的情绪推荐了一种，但你可以选择任何适合此刻的颜色。',
    'capture.tagsHelp': "使用关键词如“工作”、“家人”或“庆祝”来分类此时刻。标签有助于在报告中分组相似体验。",
    'colors.red': '红色',
    'colors.orange': '橙色',
    'colors.amber': '琥珀色',
    'colors.yellow': '黄色',
    'colors.lime': '浅绿',
    'colors.green': '绿色',
    'colors.teal': '青色',
    'colors.cyan': '蓝绿色',
    'colors.blue': '蓝色',
    'colors.indigo': '靛蓝',
    'colors.purple': '紫色',
    'colors.magenta': '洋红',
    'colors.meaning.red': '热情、愤怒、能量',
    'colors.meaning.orange': '热情、温暖、兴奋',
    'colors.meaning.amber': '自信、成功、骄傲',
    'colors.meaning.yellow': '快乐、乐观、幸福',
    'colors.meaning.lime': '成长、更新、新开始',
    'colors.meaning.green': '平衡、平静、和谐',
    'colors.meaning.teal': '清晰、专注、平和',
    'colors.meaning.cyan': '宁静、沟通',
    'colors.meaning.blue': '信任、稳定、反思',
    'colors.meaning.indigo': '直觉、智慧、深度',
    'colors.meaning.purple': '想象、灵性',
    'colors.meaning.magenta': '爱、关怀、慈悲',
    'capture.requiredFieldsWarning':
      '请填写必填字段（与谁、发生了什么、感觉如何）以保存时刻。',
    'badge.unlocked': '徽章解锁',
    'badge.gallery': '徽章画廊',
    'badge.earned': '已获得',
    'badge.activeBadge': '当前徽章',
    'badge.removeActive': '点击移除当前徽章',
    'badge.badges': '徽章',
    'common.done': '完成',
    'common.notStarted': '未开始',
    'common.available': '可用',
    'badge.gettingStarted': '入门',
    'badge.consistency': '坚持',
    'badge.depth': '深度与细节',
    'badge.emotion': '情感范围',
    'badge.insight': '自我洞察',
    'badge.nextBadge': '下一个徽章',
    'badge.openGallery': '打开徽章画廊',
    'reflection.dailyPrompt': '每日反思',
    'reflection.support': '支持',
    'reflection.reframe': '重构',
    'reflection.boundary': '界限',
    'reflection.completed': '已完成',
    'reflection.skip': '暂时跳过',
    'reflection.continue': '继续',
    'reflection.finish': '完成',
    'reflection.optional': '可选备注',
    'reflection.confidence': '信心如何？',
    'reflection.low': '低',
    'reflection.medium': '中',
    'reflection.high': '高',
    'reflection.todayTitle': '今日反思',
    'reflection.completeHint': '已完成 — 点击编辑以更新答案',
    'reflection.quickHint': '三个快速问题，保持觉察',
    'reflection.editCta': '编辑',
    'reflection.streak': '反思连续',
    'reflection.longestStreak': '最长连续',
    'reflection.daysCompleted': '完成天数',
    'reflections.title': '今日反思',
    'reflections.complete': '完成！点击查看洞察',
    'reflections.allComplete': '所有反思已完成！',
    'reflections.keepGoing': '继续努力',
    'reflections.support': '我需要外部支持吗？',
    'reflections.reframe': '如果他们是好意呢？',
    'reflections.boundary': '我需要设定界限吗？',
    'reflections.done': '完成',
    'reflections.label.support': '自我照顾',
    'reflections.label.reframe': '重构',
    'reflections.label.boundary': '界限',
    'reflections.question.support': '我需要外部支持吗？',
    'reflections.question.reframe': '如果他们是好意呢？',
    'reflections.question.boundary': '我需要设定界限吗？',
    'reflections.answer.Yes,_professional': '是的，需要专业人士',
    'reflections.answer.Yes,_a_friend': '是的，找朋友',
    'reflections.answer.Maybe': '可能',
    'reflections.answer.I\'m_okay': '我很好',
    'reflections.answer.Unsure': '不确定',
    'reflections.answer.Makes_sense': '有道理',
    'reflections.answer.Possible': '可能',
    'reflections.answer.Neutral': '中性',
    'reflections.answer.Unlikely': '不太可能',
    'reflections.answer.Yes,_right_now': '是的，现在就需要',
    'reflections.answer.Maybe_later': '以后可能',
    'reflections.answer.No': '不需要',
    'reflections.answer.Not_sure': '不确定',
    'quest.logMoment': '记录一刻',
    'quest.answerReflection': '完成每日反思',
    'quest.addDetail': '添加标签或笔记',
    'quest.completed': '已完成',
    'quest.inProgress': '进行中',
    'journey.availableNow': '当前可用',
    'journey.new': '新',
    'journey.progressNote': '进度计算为有记录的不同日期（≥1个时刻）。',
    'journey.logMoreDays': '再记录 {count} 天',
    'journey.logged': '已记录',
    'journey.dailyReflections': '每日反思',
    'journey.dailyReflectionsBenefit': '获取 XP + 1 分钟洞察',
    'journey.emotionTracking': '情绪跟踪',
    'journey.emotionTrackingBenefit': '跟踪强度随时间变化',
    'journey.patternRecognition': '模式识别',
    'journey.patternRecognitionBenefit': '查看主要主题/触发点',
    'journey.dowPatterns': '按星期的模式',
    'journey.dowPatternsBenefit': '解锁更深入的洞察',
    'journey.todayPlan': '今日计划',
    'journey.dailyReflections': '每日反思',
    'journey.dailyReflectionsBenefit': '获得 XP 和 1 分钟洞察',
    'journey.emotionTracking': '情绪跟踪',
    'journey.emotionTrackingBenefit': '随时间跟踪强度',
    'journey.patternRecognition': '模式识别',
    'journey.patternRecognitionBenefit': '查看主要主题/触发点',
    'xp.howWorks': 'XP 如何获得',
    'xp.logMoment': '记录一刻',
    'xp.completeReflections': '完成每日反思',
    'xp.depthBonus': '深度奖励（2+ 细节）',
    'xp.oncePerAction': '每个操作只奖励一次 XP',
    'levels.beginner': '初学者',
    'levels.explorer': '探索者',
    'levels.seeker': '寻求者',
    'levels.adept': '熟练者',
    'levels.navigator': '航行者',
    'levels.guide': '引路人',
    'levels.sage': '贤者',
  },
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Load saved language preference; fall back to English if invalid
    AsyncStorage.getItem('mirror-language').then((saved) => {
      if (saved === 'en' || saved === 'zh') {
        setLanguageState(saved);
      } else {
        setLanguageState('en');
      }
    });
  }, []);

  useEffect(() => {
    if (user) {
      // Future: load per-user preference from Firestore
    }
  }, [user]);

  const setLanguage = async (lang: Language) => {
    const safeLang: Language = lang === 'zh' ? 'zh' : 'en';
    setLanguageState(safeLang);
    await AsyncStorage.setItem('mirror-language', safeLang);
  };

  const t = (key: string): string => {
    const dict = translations[language] || translations.en;
    return dict[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

